Bfla module
openclarity/apiclarity pull request #117
Opened 2022-04-21 08:38 UTC by danielvladco

BFLA is a module that detects suspicious calls between internal services and warns about it, also provides a layer of visibility about user's authorization details and the kubernetes objects interaction

2022-04-22 11:21 UTC, klyr reviewed
I didn't review the UI part.
But the rest is ok for me

2022-04-22 11:21 UTC, klyr commented on backend/pkg/modules/internal/bfla/init.go
> +		hmap[h.Key] = h.Value
The key should be lowercased, and all reference to constant headers name should be used lowercased.

2022-04-22 11:21 UTC, klyr commented on backend/pkg/modules/internal/bfla/bfladetector/user_detection.go
> +	authz, ok := headers["authorization"]
GetUserID is given a headers map where keys can be mixed case.
I case of a `AuThorIzation` header name, which is valid, you won't be have to get the userID.

2022-04-22 11:21 UTC, klyr commented on backend/pkg/modules/internal/bfla/recovery/state.go
> +			log.Infof("nothing to update for module=%s; apiID=%d", key.modName, key.apiID)
Debugf

2022-04-26 15:28 UTC, danielvladco commented on backend/pkg/modules/internal/bfla/init.go
> +		err = e.accessor.CreateAPIEventAnnotations(ctx, modName, eventID, core.AlertWarnAnn)
not yet

2022-04-27 13:39 UTC, galiail commented on ui/src/modules/bfla/index.js
> +                    type={bflaStatus === BFLA_STATUS_TYPES_MAP.LEGITIMATE.value ? 'deny' : 'approve' }
Maybe add a const for "deny" and "approve". The strings seem to be repeating on the code

2022-04-27 13:39 UTC, galiail commented on ui/src/modules/bfla/BflaApiInventory.js
> +        {
Maybe create an empty item const and reuse it instead of duplicating?

2022-05-05 15:51 UTC, aduminuc requested changes

2022-05-05 15:51 UTC, aduminuc commented on backend/pkg/modules/internal/bfla/readme.md
> +The user can also stop stat and reset learning.
The user can also stop**,** sta**r**t**,** and reset learning.

2022-05-06 14:46 UTC, aduminuc approved these changes
LGTM

2022-05-06 15:14 UTC, merged